### ISSUE TITLE
How to use SQLLinq with Xamarin

### ISSUE THREAD

**Issue by mazloumi** [dkackman/SqlLinq#4]
Hi,  I tried to install SQLLinq as a nuget into my Xamarin project but it failed. I also tried to directly compile the source into my probject you have 2 libraries GoldParser and TypeLoader that are in the project as DLL. Any suggestion what I could do?
Thanks

**Comment by dkackman** [comment]
The project is a /net 4.5 dll and isn't portable. Unfortunately I'm not sure it can be converted to one. TypeLoader is some of my code that I might be able to convert, though it uses a lot of reflection, so might be iffy. Gold parser comes from Here: http://www.goldparser.org/ and hasn't been updated in quite some time. I'll play around with a few things but you might be out of luck.

**Comment by dkackman** [comment]
stale
